In [34]:
x = 10
print (x)

10


**working with odd numbers

In [35]:
        def oddNo():
            a = []
        while a<50:
            num=a.append()
            print(num)


        #     if a > 10 and a <50 and a/2>0:
        #         print('odd number between 10 and 50')
        #     else:
        #             print('try again')
        oddNo()


NameError: name 'a' is not defined

**working with numpy

In [ ]:
import numpy as np

In [66]:
ar = np.array([[4,36,98,26],[27,np.nan,42,34],[32,7,np.nan,17]])
print(type(ar))
print(type(ar.shape))
ar.shape
print(ar)

<class 'numpy.ndarray'>
<class 'tuple'>
[[ 4. 36. 98. 26.]
 [27. nan 42. 34.]
 [32.  7. nan 17.]]


In [ ]:
ar2 = np.array([[7,89,9],[58,65]])
print(type(ar2))
print(ar2)
ar2.shape

In [ ]:
ar3 = np.array([[7,89,9],[58,65,]])
print(type(ar3))
print(ar3)
ar3.shape

In [37]:
ar4 = np.isnan([[4,36,98,26],[27,np.nan,42,34],[32,7,np.nan,17]])
print(type(ar4))
print(ar4)
ar4.shape

<class 'numpy.ndarray'>
[[False False False False]
 [False  True False False]
 [False False False False]]


(3, 4)

In [67]:
# ar5 = np.isan([[4,36,98,26],[27,np.nan,42,34],[32,7,np.nan,17]])
print(type(np.nan))
ar5 = np.isnan(ar)
# ar5.shape
# print(type(ar5))
# print(ar5)
ar5

<class 'float'>


array([[False, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [68]:
ar[ar5]=0
ar

array([[ 4., 36., 98., 26.],
       [27.,  0., 42., 34.],
       [32.,  7.,  0., 17.]])

In [69]:
type(np.nan)

float

**replace zero in array with mean of entire array

**research on why np.nan is a float data type

In [71]:
ar6 = np.array([[4,36,98,26],[27,8,42,34],[32,7,10,17]])
print (np.mean(ar6))

28.416666666666668
